---
title: "Grade 7 Maths"
author: "Prem"
date: "Monday, January 18, 2016"
output: html_document
---
## Addition and subtraction

* **Subtracting small positive numbers by large negatives**
    * Factor out the expression with a negative sign to make calculation easier
    * 0.79 - 79.1 - 58.1
    * -(-0.79 + 79.1 + 58.1) factor out the negative sign
    * -(136.41) calculate the inside of the bracket
    * -136.41

## Multiplication and division

### Negative

* **Is an expression negative or positive?** [tut](https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-negative-numbers-multiply-and-divide/cc-7th-exponents-negative-base/v/thinking-about-the-sign-of-expressions)
    * Count the number of negative signs. An expression with a even number of negative signs is equal, a number with a odd number of negative signs is negative
    * **example**: $
    
## Exponents and Powers

### Laws of Exponents

* **Exponents with negative bases**
    * **example 1**: $-2^2$ 
    * $-(2*2)$
    * $-4$
    * ***note***: `Order of Operation` = exponents are raised before multiplication. Thus $-2^2$ equals $-(2^2)$ which will always be negative, no matter if the exponent is odd or equal. If you want a positive result, put paranthesis around base *then* write exponent as shown below.  
    * **example 2**: $(-2)^2$
    * $(-2)*(-2)$
    * $4$
    * ***note***: whenever you raise a negative base by an odd exponent, you will get an negative result, because the negatives do not cancel out
        * $(neg)^ odd = neg$

* **Exponents with negative fractional bases**
    ** **example**: $(-2/8)^2$ 
    * $(-2/8)*(-2/8)$
    * $4/16$
    



## Algebraic Equations [tut](https://www.khanacademy.org/math/algebra/introduction-to-algebra/overview_hist_alg/v/the-beauty-of-algebra?ref=staff_video_picks)

* Useful tool for finding out stuff in real life, even if it isn't there to count or does not exist
* Equation is a statement that helps us understand the equality between variables and constants
* Variables can be any value and are respresented by letters `a`,`b`,`x` etc
* Constants are fixed values. `x+3=7` 3 and 7 are constants, `x` variable
* one side of the equation is equal to the other. To find out the mystery value `x`, we do the same things to both sides to keep the scales balanced 

* **example**: You have three pokeballs which cost $9. How much do they cost each? 
    * write as equation: 3P = $9
    * 1. Keep the scales balanced by doing the same to each side
    * Let's try getting P on it's own so we're only left with 1/3rd, aka one Pokeball. 
    * Multiply by 1/3 or divide by 3
    * $3P/3 = $9/3$ 
    * $P = $3$ 
### Linear equations and inequalities 


* **Linear Equation word problem** 
    ***example***: Ash has captured a Squirtle. The Squirtle had an XP of 20 to begin with and grows by 5XP with each battle. His total XP is 60.  Write an equation to determine the number of battles(b) you've had with Squirtle.
    * $20+5b=60$
    * take away the initial 20xp. $5b=40$
    * take away the 5xp $b=8$. You've had 8 battles since capturing Squirtle

* **Inequalities** [explanation](http://www.mathsisfun.com/algebra/inequality.html)
    * Inequalities tell us about the relative size of two values. Maths is not always about "equals". Sometimes we want to know if something is bigger or smaller. 
    * i.e. Harry and Ron have a wand duel, and Harry wins! We don't know by how many points Harry won, we just know it was more than Ron. 
    * this can be written as $H > R$, where $H$ is harry's points and $R$ is Ron's points.
    * **symbols**
    * `x < 5` x is to the left of 5 (less than)
    * `x > 5` x is to the right of 5 (more than)
    * **One step inequalities**
    * Red has $1000 to spend, each rare candy cost $4. How many rare candies can he buy? 
    * Set up equations, where `x` = rare candies
    * $4x < 1000$ = Each rare candy cost $4 and the total must be less than a thousand dollars
    * $1/4*(4x) < 1/4*(1000)$ Multiply out to get X on it's own. Multiplying inequality by positive number, so sign remains the same
    * $x < 250$ = Red must buy less than 250 rare candies.
    * Any amount of rare candies less than 250 is the solution
    * ***note***: You swap inequality sign when multiplying/dividing both sides by a negative number. 
    * $1<2$ = one is less than two
    * $-1>-2$ = negative two is MORE negative than negative one, hence sign is swapped 
    


### Quadratics

*   **Factoring simple expressions** = put expression into lowest terms and make it easier to answer 
* Factoring Linear Binomials
    * `Binomial` = sum of two terms. `linear` = expression with no exponents or square roots  
    * **example** 
    * $4x+18$ 
    * Find greatest common factor and multiply out
    * $2(2x) + 2(9)$
    * $2(2x+9)$


## Proportions

Pikachu is poisoned, so we loose 5 HP for every 2 steps we take. If we have 30 HP, how many steps can we take? 

* **Algebra**
    * Flip, and destroy
    * $5/2 = 30/x$
    * 
    
    
* **multiplication**


## Statistics [tut1](http://mathbench.umd.edu/modules/visualization_log-transformations/page04.htm)   [tut2](http://www.biostathandbook.com/transformation.html)   [Rtut](http://www.r-statistics.com/2013/05/log-transformations-for-skewed-and-wide-distributions-from-practical-data-science-with-r/)

## Compound events and sample spaces

* **Probabillity of compound event**
    * **example**: You're at a clothing store. You get to pick from four pieces of clothing (shirt, jean, underwear, hat) and from 3 colours (blue, purple, orange). If you pick by the clothing and colour by random, what are the chances you'll have an orange hat? 
        * probabillity = favourable outcomes / total possible outcomes
        * Draw a compound space  
        
|        | shirt        | jean        | underwear        | hat        |
|--------|--------------|-------------|------------------|------------|
| blue   | blue shirt   | blue jean   | blue underwear   | blue hat   |
| purple | purple shirt | purple jean | purple underwear | purple hat |
| orange | orange shirt | orange jean | orange underwear | orange hat |
        
        * There is 12 (3*4) possible combinations in total. If we pick randomly all choices are equally likely
        * There is only one favourable outcome of an orange hat 
        * $probabillity of randomly picking a orange hat = 1/12$
        
* **Counting Principle**
    * Counting the total number of possible outcomes/combinations. e.g. ways to get dressed or types of dishes. 
    * **example**: You are designing your next gun. The gun has 3 types of ammo, 13 types of barrels, 7 types of grips, 4 types of sights and 2 types of colour. How many different guns can you create? 
        * Total number of guns can be found by multiplying the number of options of each gun component
        * Total number of guns = $3?13?7?4?2 = 2184$. You can create $2184$ different guns

* **Log Transformations**
    * Data differs by orders of magitude (10, 100, 1000, 10000)
    * To make modelling easier and appearance on graph nicer, log transform
    * Make skewed data normally distributed
    * Makes patterns more visible
    
    
* **Confidence Intervals** 
    * A range of numbers (interval) in which you are 95% sure the true mean will lay
    * *There is a 95% chance that average weight of Pokemon will lay between 33 and 53. There is a margin error of 10grams*


xmean <- sd(pokemon$weight)
xsd <- sd(pokemon$weight)
n <- length(pokemon$weight)

LCI <- xmean-1.96*xsd/sqrt(n)
UCI <- xmean+1.96*xsd/sqrt(n)

## Basic Geometry

### Trianlges

* **Triangle Inequality Theorem** any side of triangle must be less than sum of the two other sides
    * a < (b+c), b < (a+c), c < (c+b)
    
### Scale Drawings

Peter just buried a treasure chest on a remote island and is making a map so he can find it later. One of the key landmarks in the area is a small rectangular hut, 5m by 8m.  

The map's scale is 2 units: 1m. Help him draw...

 * Convert 5m into units
    * $5 ~m~ * ~2~ units / 1 m$
    * 5 ~~m~~ * 2 units / 1 ~~m~~
    * $= 10 units$
 * Convert 8m into units
    * $8m * 2 units / 1 m$
    * 8 ~~m~~ * 2 units / 1 ~~m~~
    * $= 16 units$
 
## Improvements

Add history to each section and uses   